FROM python:3.12-slim
WORKDIR /workshop
RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*
COPY docker/requirements-base.txt .
RUN pip install --no-cache-dir -r requirements-base.txt
COPY . .
CMD ["/bin/bash"]
